package owg;

import com.google.common.collect.ImmutableList;

import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import owg.biomes.BiomeList;
import owg.config.ConfigOWG;
import owg.events.Events;
import owg.language.OWGLanguage;
import owg.support.Support;
import owg.world.WorldTypeOWG;

@Mod(modid = OWG.MODID, version = OWG.VERSION, acceptedMinecraftVersions = "[1.8.9]")
public class OWG
{
    public static final String MODID = "OWG";
    public static final String NAME = "Old World Gen";
    public static final String VERSION = "1.0.8";

    @Instance(MODID)
    public static OWG instance;

    public static final WorldTypeOWG worldtype = (new WorldTypeOWG(MODID));

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        instance = this;
        ModMetadata metadata = event.getModMetadata();
        metadata.autogenerated = false;
        metadata.name = EnumChatFormatting.BOLD + NAME;
        metadata.description = "The good old world gen from back in the days.";
        metadata.version = VERSION;
        metadata.url = "https://github.com/Adahel/Old-World-Gen";
        metadata.authorList = ImmutableList.of("ted80", "Adahel");
        metadata.credits = "Thanks Nicholai (mrburger) for creating the y emulator and ocean deepen for generate ocean monuments.";
        metadata.logoFile = MODID + ".png";

        OWGLanguage.init();
        ConfigOWG.init(event);
        BiomeList.init();
    }

    @EventHandler
    public void Init(FMLInitializationEvent event)
    {
        if (event.getSide() == Side.CLIENT)
        {
            Events.initClient();
        }
        Events.init();
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event)
    {
        Support.init();
    }
}
